FROM python:3.9-slim AS builder

LABEL maintainer="Utkrist Ark"
LABEL description="a dockerfile for ML model"

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/* 


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY . .


FROM python:3.9-slim

WORKDIR /app

ENV PYTHONPATH="/app"

COPY --from=builder /app /app

RUN pip install --no-cache-dir -r /app/requirements.txt

EXPOSE 8501

CMD ["python3", "-m", "streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]

        
