version: '3.8'

networks:
  ipl-match-predictor-_app_network:
    driver: bridge

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipl-match-predictor-streamlit
    ports:
      - "8501:8501"
    networks:
      -   ipl-match-predictor-_app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ipl-match-predictor--nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - streamlit
    networks:
      -   ipl-match-predictor-_app_network