version: '3.8'

networks:
  ipl-match-predictor-app-network:
    driver: bridge

services:
  go_app:
    build:
      context: ./loginpage
      dockerfile: Dockerfile
    image: ipl-match-predictor-go
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - ipl-match-predictor-app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipl-match-predictor-streamlit
    ports:
      - "8501:8501"
    networks:
      - ipl-match-predictor-app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ipl-match-predictor-nginx
    ports:
      - "80:80"
    volumes:
      - ./loginpage/static:/app/static  
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go_app
      - streamlit
    networks:
      - ipl-match-predictor-app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - ipl-match-predictor-app-network
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
