FROM python:3.9-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --target=/app/dependencies -r requirements.txt

COPY . .

FROM gcr.io/distroless/python3

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 8501

CMD ["app.py", "--server.port=8501", "--server.address=0.0.0.0"]
