version: "3"
services:
  sonarqube:
    image: sonarqube:community
    ports:
      -  "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE= "true"
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_data:/var/lib/postgresql/data

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: sonar_scanner
    volumes:
      - ./project:/usr/src
    working_dir: /usr/src
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  sonarqube_data:

